version: '3'
services:
  imdb:
    image: docker.elastic.co/princeraj/imdb:v1
    container_name: imdb
    environment:
    - "IMDB_ENV=production"
    - "SQLDb=test-accapi"
    - "SQLHost=35.245.75.150"
    - "SQLPassword=1001611_appbase"
    - "SQLUser=postgres"
    - "Admins=raaz.crzy@gmail.com"
    - "ElasticURL=https://ImOlGIeji:8d702398-0146-4f8e-91e0-e4e6c42046e8@scalr.api.appbase.io"
    - "MovieIndex=imdb"
    - "LogLevel=INFO"
    ports:
      - 8000:8000